x-logging: &loki-logging
  logging:
    driver: loki
    options:
      loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
      mode: non-blocking
      max-buffer-size: 4m
      loki-retries: "3"

services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - type: bind
        source: ./deployment/loki/local-config.yaml
        target: /etc/loki/local-config.yaml
    depends_on:
      - grafana
  elasticsearch:
    <<: *loki-logging
    container_name: temporal-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 30s

  postgresql:
    <<: *loki-logging
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRESQL}
      POSTGRES_USER: ${SERVICE_USER_POSTGRESQL}
    image: postgres:${POSTGRESQL_VERSION}
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SERVICE_USER_POSTGRESQL}"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 30s

  temporal-setup:
    <<: *loki-logging
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    container_name: temporal-setup
    restart: on-failure:6
    depends_on:
      postgresql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      DB: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_DEFAULT_PORT}
      POSTGRES_USER: ${SERVICE_USER_POSTGRESQL}
      POSTGRES_PWD: ${SERVICE_PASSWORD_POSTGRESQL}
      POSTGRES_SEEDS: postgresql
      SQL_PASSWORD: ${SERVICE_PASSWORD_POSTGRESQL}
      ES_HOST: elasticsearch
      ES_PORT: 9200
      ES_SCHEME: http
      ES_VERSION: v7
      ES_VISIBILITY_INDEX: temporal_visibility_v1_dev
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/sh"]
    command: /scripts/setup-postgres-es.sh

  temporal-history:
    <<: *loki-logging
    container_name: temporal-history
    depends_on:
      temporal-setup:
        condition: service_completed_successfully
    environment:
      DB: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_DEFAULT_PORT}
      POSTGRES_USER: ${SERVICE_USER_POSTGRESQL}
      POSTGRES_PWD: ${SERVICE_PASSWORD_POSTGRESQL}
      POSTGRES_SEEDS: postgresql
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      TEMPORAL_HISTORY_NAMESPACEDEFAULT_ARCHIVAL_FILESTORE: enabled
      TEMPORAL_VISIBILITY_NAMESPACEDEFAULT_ARCHIVAL_FILESTORE: enabled
      TEMPORAL_SERVICES: history
      PROMETHEUS_ENDPOINT: 0.0.0.0:8000
      ENABLE_ES: true
      ES_SEEDS: elasticsearch
      ES_VERSION: v7
      TEMPORAL_CLI_ADDRESS: temporal-nginx:7233
      TEMPORAL_ADDRESS: temporal-nginx:7233
    image: temporalio/server:${TEMPORAL_VERSION}
    restart: on-failure
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-matching:
    <<: *loki-logging
    container_name: temporal-matching
    depends_on:
      - temporal-history
    environment:
      DB: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_DEFAULT_PORT}
      POSTGRES_USER: ${SERVICE_USER_POSTGRESQL}
      POSTGRES_PWD: ${SERVICE_PASSWORD_POSTGRESQL}
      POSTGRES_SEEDS: postgresql
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      TEMPORAL_HISTORY_NAMESPACEDEFAULT_ARCHIVAL_FILESTORE: enabled
      TEMPORAL_VISIBILITY_NAMESPACEDEFAULT_ARCHIVAL_FILESTORE: enabled
      TEMPORAL_SERVICES: matching
      PROMETHEUS_ENDPOINT: 0.0.0.0:8001
      ENABLE_ES: true
      ES_SEEDS: elasticsearch
      ES_VERSION: v7
      TEMPORAL_CLI_ADDRESS: temporal-nginx:7233
      TEMPORAL_ADDRESS: temporal-nginx:7233
    image: temporalio/server:${TEMPORAL_VERSION}
    restart: on-failure
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-frontend:
    <<: *loki-logging
    container_name: temporal-frontend
    depends_on:
      - temporal-matching
    environment:
      DB: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_DEFAULT_PORT}
      POSTGRES_USER: ${SERVICE_USER_POSTGRESQL}
      POSTGRES_PWD: ${SERVICE_PASSWORD_POSTGRESQL}
      POSTGRES_SEEDS: postgresql
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      TEMPORAL_HISTORY_NAMESPACEDEFAULT_ARCHIVAL_FILESTORE: enabled
      TEMPORAL_VISIBILITY_NAMESPACEDEFAULT_ARCHIVAL_FILESTORE: enabled
      TEMPORAL_SERVICES: frontend
      FRONTEND_GRPC_PORT: 7237
      PROMETHEUS_ENDPOINT: 0.0.0.0:8002
      ENABLE_ES: true
      ES_SEEDS: elasticsearch
      ES_VERSION: v7
      TEMPORAL_CLI_ADDRESS: temporal-nginx:7233
      TEMPORAL_ADDRESS: temporal-nginx:7233
    image: temporalio/server:${TEMPORAL_VERSION}
    restart: on-failure
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-frontend2:
    <<: *loki-logging
    container_name: temporal-frontend2
    depends_on:
      - temporal-matching
    environment:
      DB: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_DEFAULT_PORT}
      POSTGRES_USER: ${SERVICE_USER_POSTGRESQL}
      POSTGRES_PWD: ${SERVICE_PASSWORD_POSTGRESQL}
      POSTGRES_SEEDS: postgresql
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      TEMPORAL_HISTORY_NAMESPACEDEFAULT_ARCHIVAL_FILESTORE: enabled
      TEMPORAL_VISIBILITY_NAMESPACEDEFAULT_ARCHIVAL_FILESTORE: enabled
      TEMPORAL_SERVICES: frontend
      # set different frontend grpc port
      FRONTEND_GRPC_PORT: 7236
      # set different membership port than temporal-frontend
      FRONTEND_MEMBERSHIP_PORT: 6936
      PROMETHEUS_ENDPOINT: 0.0.0.0:8004
      ENABLE_ES: true
      ES_SEEDS: elasticsearch
      ES_VERSION: v7
      TEMPORAL_CLI_ADDRESS: temporal-nginx:7233
      TEMPORAL_ADDRESS: temporal-nginx:7233
    image: temporalio/server:${TEMPORAL_VERSION}
    restart: on-failure
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-worker:
    <<: *loki-logging
    container_name: temporal-worker
    depends_on:
      - temporal-nginx
    environment:
      DB: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_DEFAULT_PORT}
      POSTGRES_USER: ${SERVICE_USER_POSTGRESQL}
      POSTGRES_PWD: ${SERVICE_PASSWORD_POSTGRESQL}
      POSTGRES_SEEDS: postgresql
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      TEMPORAL_HISTORY_NAMESPACEDEFAULT_ARCHIVAL_FILESTORE: enabled
      TEMPORAL_VISIBILITY_NAMESPACEDEFAULT_ARCHIVAL_FILESTORE: enabled
      TEMPORAL_SERVICES: worker
      PROMETHEUS_ENDPOINT: 0.0.0.0:8003
      # set to nginx
      PUBLIC_FRONTEND_ADDRESS: temporal-nginx:7233
      TEMPORAL_CLI_ADDRESS: temporal-nginx:7233
      TEMPORAL_ADDRESS: temporal-nginx:7233
      ENABLE_ES: true
      ES_SEEDS: elasticsearch
      ES_VERSION: v7
    image: temporalio/server:${TEMPORAL_VERSION}
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-create-namespace:
    <<: *loki-logging
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    container_name: temporal-create-namespace
    restart: on-failure:5
    depends_on:
      - temporal-nginx
    environment:
      TEMPORAL_ADDRESS: temporal-nginx:7233
      DEFAULT_NAMESPACE: default
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/sh"]
    command: /scripts/create-namespace.sh

  temporal-admin-tools:
    <<: *loki-logging
    container_name: temporal-admin-tools
    depends_on:
      - temporal-nginx
    environment:
      TEMPORAL_CLI_ADDRESS: temporal-nginx:7233
      TEMPORAL_ADDRESS: temporal-nginx:7233
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal-nginx
    environment:
      SERVICE_URL_TEMPORAL_UI_8080:
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
      TEMPORAL_CLI_ADDRESS: temporal-nginx:7233
      TEMPORAL_ADDRESS: temporal-nginx:7233
    image: temporalio/ui:${TEMPORAL_UI_VERSION}

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.0
    environment:
      SERVICE_URL_PROMETHEUS_9090:
    volumes:
      - type: bind
        source: ./deployment/prometheus/config.yml
        target: /etc/prometheus/prometheus.yml
    depends_on:
      - temporal-worker

  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.16
    build: "./deployment/grafana"
    environment:
      SERVICE_URL_GRAFANA_3000:
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - type: bind
        source: ./deployment/grafana/provisioning/datasources
        target: /etc/grafana/provisioning/datasources
    depends_on:
      - prometheus

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.37
    networks:
      - temporal-network

  otel-collector:
    image: otel/opentelemetry-collector:0.47.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - type: bind
        source: ./deployment/otel/otel-config.yaml
        target: /etc/otel-collector-config.yaml
    depends_on:
      - jaeger-all-in-one
    networks:
      - temporal-network

  temporal-nginx:
    <<: *loki-logging
    image: nginx:1.22.1
    container_name: temporal-nginx
    restart: unless-stopped
    depends_on:
      - temporal-frontend
      - temporal-frontend2
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - temporal-network
